name: Automated API tests

on:
  push:
    paths-ignore:
      - 'webroot/**'
      - 'web/**'

  pull_request:
    paths-ignore:
      - 'webroot/**'
      - 'web/**'

jobs:
  test:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: 'latest' # or pin to an specific version, e.g. "v0.6.10"

      - name: Earthly version
        run: earthly --version

      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - uses: actions/checkout@v3

      - name: Run API tests
        run: earthly +api-tests
