name: Browser Tests

on: [push, pull_request_target]

jobs:
  cypress-run:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Run Browser tests
        run: cd test/automated/browser && ./run.sh
