name: Browser Tests

on:
  push:
    paths:
      - web/**
  pull_request_target:
    paths:
      - web/**
jobs:
  cypress-run:

    runs-on: ubuntu-latest
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content_newer'
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: Run Browser tests
        run: cd test/automated/browser && ./run.sh
